"""Add image_url and type to Equipment

Revision ID: 1f5a8af6d7ff
Revises: e641dc5ff133
Create Date: 2025-11-20 12:05:57.970013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f5a8af6d7ff'
down_revision: Union[str, None] = 'e641dc5ff133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipments', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('equipments', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipments', 'type')
    op.drop_column('equipments', 'image_url')
    # ### end Alembic commands ###
